name: 'Unlock Keyring'
description: 'GitHub Action to unlock Gnome keyring daemon in Ubuntu'
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
# outputs:
#   time: # id of output
#     description: 'The time we we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'unlock'
  color: 'yellow'
