name: Smoke Test
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
  workflow_dispatch:

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -qq python3-keyring
      - uses: actions/checkout@v2
      - uses: ./
      - run: python3 -c "import keyring; keyring.set_password('test', 'user', 'password')"

  test-docker: # make sure the action works in a Docker container
    container: node:lts
    runs-on: ubuntu-latest
    steps:
      - run: apt-get install -qq python3-keyring
      - uses: actions/checkout@v2
      - uses: ./
      - run: python3 -c "import keyring; keyring.set_password('test', 'user', 'password')"
